In [1]:
# Import necessary libraries
import pandas as pd
import plotly.graph_objects as go
import dalmatian
from google.cloud import storage
import matplotlib.pyplot as plt
import networkx as nx
from networkx.drawing.nx_pydot import graphviz_layout

import numpy as np

import sys
import os
sys.path.append('..')  
import model_helper 
from model_helper import add_uniform_noise_and_normalize
from helper import *
from plotly_helper import *

In [2]:
# Function to load data
def load_data(patient_id, wbc_file, treatment_file):
    # Load WBC and treatment data
    wbc_df = pd.read_csv(wbc_file)
    treatment_df = pd.read_csv(treatment_file, sep='\t')
    
    # Get input files from Terra through dalmatian
    workspace = 'broad-firecloud-ibmwatson/TAG_CLL_Clonal_Kinetic_UMI_PrAN'
    wm = dalmatian.WorkspaceManager(workspace)
    participants = wm.get_participants()
    
    # Load additional data for the patient
    cluster_CCF_df = pd.read_csv(participants.loc[patient_id]['cluster_ccfs'], sep='\t')
    abundance_df = pd.read_csv(participants.loc[patient_id]['abundances_tsv'], sep='\t')
    mcmc_df = pd.read_csv(participants.loc[patient_id]['cell_population_mcmc_trace'], sep='\t')
    tree_df = pd.read_csv(participants.loc[patient_id]['tree_tsv'], sep='\t')
    
    return wbc_df, treatment_df, cluster_CCF_df, abundance_df, mcmc_df, tree_df

# Function to filter data for a specific patient
def filter_patient_data(wbc_df, patient_id):
    wbc_df_patient = wbc_df[wbc_df['Patient'] == patient_id]
    wbc_df_patient.reset_index(drop=True, inplace=True)
    
    # Filter out rows where ALC is empty or NaN
    wbc_df_patient = wbc_df_patient[wbc_df_patient['ALC'].notna() & (wbc_df_patient['ALC'] != '')]
    wbc_df_patient.reset_index(drop=True, inplace=True)
    
    times_sample = [int(i) for i in wbc_df_patient.loc[wbc_df_patient.Sample.notna(), 'Day'].tolist()]
    alc_all = [float(i) for i in wbc_df_patient['ALC'].tolist()]
    
    
    alc_count_sample = [float(i) for i in wbc_df_patient.loc[wbc_df_patient.Sample.notna(), 'CLL_est'].tolist()]
    all_times = [int(i) for i in wbc_df_patient['Day'].to_list()]
    
    return wbc_df_patient, times_sample, alc_all, alc_count_sample, all_times





In [3]:
end_treatment_df = pd.read_csv("../CLL8_end_treatment.csv")

In [4]:
# Input patient information
# Input patient information
patient_id = 'RP-1895_FI-07'
wbc_file = '../combined_FI_alc_updated.csv'
treatment_file = '../GCLL_treatment.txt'
UMI_start = 6
UMI_end = 8
treatment_start = 0


In [5]:
# Manually verify the sample list order is correct

In [6]:

sample_list = ['RP-1895_9211-C1D1_unknown_v1_Exome_OnPrem-RP-1895_262-SAL_unknown_v1_Exome_OnPrem', 'RP-1895_9403-C2D28_unknown_v1_Exome_OnPrem-RP-1895_262-SAL_unknown_v1_Exome_OnPrem', 'RP-1895_9583-C4D28_unknown_v1_Exome_OnPrem-RP-1895_262-SAL_unknown_v1_Exome_OnPrem', 'RP-1895_9727-C6D28_unknown_v1_Exome_OnPrem-RP-1895_262-SAL_unknown_v1_Exome_OnPrem', 'SM-N57VD_RP-1895_262-SAL_unknown_v1_Exome_OnPrem_pair', 'SM-N57VE_RP-1895_262-SAL_unknown_v1_Exome_OnPrem_pair', 'SM-N57VA', 'SM-N57VB']

In [7]:
# Output file

In [8]:
outputfile_name = "FI_subplot_combined_07_wbc_updated.html"

Update patient specific information in the below cell 

In [9]:
# Get the treatment duration 

treatment_end = 1636

In [10]:
treatment_end

1636

In [11]:

wbc_df, treatment_df, cluster_CCF_df, abundance_df, mcmc_df, tree_df = load_data(patient_id, wbc_file,treatment_file )

# Filter data for the specific patient
wbc_df_patient, times_sample,alc_count,alc_count_sample, all_times = filter_patient_data(wbc_df, patient_id)

# Plot CLL count over time and save as HTML
CLL_plot_html = plot_CLL_count(patient_id, times_sample, alc_count_sample, UMI_start, UMI_end, treatment_start, treatment_end, fludarabine_treatment_1=(57, 61),
               fludarabine_treatment_2=(84, 88)) 
    




In [12]:
times_sample

[-2, 59, 110, 166, 348, 705, 1069, 1545]

In [13]:
alc_count_sample

[229.57, 157.26, 83.57, 25.17, 3.99, 0.32093, 0.29799, 0.17017]

In [14]:
wbc_table_html = plot_metadata_table(wbc_df_patient, patient_id )

In [15]:
tree_df

n_iter                                         likelihood           edges
0     249  [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, ...  1-2,1-3,None-1

In [16]:
 plot_ccf_html = plot_ccf(cluster_CCF_df, times_sample, treatment_df,)

In [17]:
ccf_tree_html = plot_ccf_tree_combined(
    tree_df=tree_df,
    tree_selected=0
    ,
    ccf_df=cluster_CCF_df,
    times_sample=times_sample,
    treatment_df=treatment_df,
 

)

In [18]:
cluster_list, cluster_abundance = model_helper.get_abundance(abundance_df, mcmc_df, sample_list)
subclone_sample, log_subclone_sample = model_helper.calc_subclone(alc_count_sample, cluster_abundance, cluster_list)
all_abundance = model_helper.get_all_abundance(cluster_list, mcmc_df, sample_list, times_sample, )

In [19]:
#  Add noise to all abundance

import random 
random.seed(42)
def add_uniform_noise_and_normalize(lst, low=0, high=0.01):
    
    # Add uniform noise
    noisy_lst = [x + random.uniform(low, high) for x in lst]

    
    # Normalize the list
    total_sum = sum(noisy_lst)
    
    normalized_lst = [x / total_sum for x in noisy_lst]

    return normalized_lst


subclone_cluster_iter = {}
# Iterate through each cluster
for cluster, iterations in all_abundance.items():
   
    # Iterate through each iteration in the cluster
    for iteration, value in iterations.items():
        # If the iteration is not in the new dict, add it
        if iteration not in subclone_cluster_iter:
            subclone_cluster_iter[iteration] = {}
        # Add the cluster and its value to this iteration
        subclone_cluster_iter[iteration][cluster] = value

        
        
noise_added_iter = {}

for iteration, abundances in subclone_cluster_iter.items():
    
    transposed_data = {i: list(values) for i, values in enumerate(zip(*abundances.values()), start=1)}
    
    noise_added_iter[iteration] = {}
    for time_point, abundance in transposed_data.items():
        
#         print(time_point, abundance)
        noise_abundance = add_uniform_noise_and_normalize(abundance)
    
#         print(noise_abundance)

        noise_added_iter[iteration][time_point] = add_uniform_noise_and_normalize(abundance)

    
noise_added_all_abundance = {}
for iteration, abundances in noise_added_iter.items():
    original_format = {i + 1: list(values) for i, values in enumerate(zip(*abundances.values()))}
    noise_added_all_abundance[iteration] = original_format
    
    
noise_added_original_all_abundances = {}

for iteration, abundances in noise_added_all_abundance.items():
    
    for cluster, abundance_value in abundances.items():
        if cluster not in noise_added_original_all_abundances:
            noise_added_original_all_abundances[cluster] = {}
        noise_added_original_all_abundances[cluster][iteration] = abundance_value
            

In [20]:
subclone_sample_mcmc_with_uniform_noise, log_subclone_sample_mcmc_with_uniform_noise = model_helper.calc_subclone(alc_count_sample, noise_added_original_all_abundances, cluster_list, input_type = "mcmc")

In [21]:
times_aft_tx = [x for x in all_times if x > treatment_start]
times_aft_tx.insert(0, treatment_end)

# Set the extrapolate time after treatment
extrapolate_start_idx = 1

In [22]:
times_sample

[-2, 59, 110, 166, 348, 705, 1069, 1545]

In [23]:
times_sample[extrapolate_start_idx:]

[59, 110, 166, 348, 705, 1069, 1545]

In [24]:
# Generate Plotly plot
subclone_plot_html = plot_subclones(cluster_list, times_sample, alc_count_sample, log_subclone_sample, extrapolate_start_idx, times_aft_tx, treatment_df, treatment_end, fi_modeling=True)


In [25]:
linear_model_mcmc_html = plot_linear_model_mcmc(cluster_list,times_sample,  alc_count_sample, log_subclone_sample_mcmc_with_uniform_noise,extrapolate_start_idx,times_aft_tx,treatment_df, treatment_end, fi_modeling=True)  

In [26]:
times_sliced_aft = [int(i) for i in wbc_df_patient[wbc_df_patient['Day'] > 0]['Day'].values  if int(i) > 0]

In [27]:
# Needs to manually check times_sliced_aft

In [28]:
times_sliced_aft

[26,
 54,
 59,
 75,
 82,
 87,
 103,
 110,
 138,
 166,
 257,
 348,
 432,
 516,
 600,
 705,
 796,
 894,
 971,
 1069,
 1160,
 1258,
 1356,
 1449,
 1545]

In [29]:
len(times_sliced_aft)

25

In [30]:
index_samples_model = slice(1,8)

# index_samples_model is the index of the samples after treatment. For instance, slice(1,7) means sample 2, 3, 4, 5,6, 7

X, y = create_inputs(times_sliced_aft, log_subclone_sample_mcmc_with_uniform_noise,2, index_samples_model, times_sample)



In [31]:
y

[None,
 None,
 array([3.31172444, 4.50346602, 3.67744214]),
 None,
 None,
 None,
 None,
 array([2.66030487, 3.86310297, 3.07646208]),
 None,
 array([1.23014854, 2.6350081 , 2.05571066]),
 None,
 array([-0.06121321,  0.67210701,  0.08820781]),
 None,
 None,
 None,
 array([-2.67633249, -2.23767253, -1.92754734]),
 None,
 None,
 None,
 array([-2.13280265, -4.18385731, -1.80584773]),
 None,
 None,
 None,
 None,
 array([-2.81004426, -5.53082555, -2.24378795])]

In [32]:
wbc_aft_tx = wbc_df_patient[wbc_df_patient.Day > treatment_start]['CLL_est'].to_list()
wbc_model = [i for i in wbc_aft_tx if i > 0]

In [33]:
wbc_model

[267.67,
 170.07,
 157.26,
 81.3,
 92.33,
 55.47,
 54.6,
 83.57,
 42.09,
 25.17,
 12.4,
 3.99,
 3.211,
 2.3085,
 1.1875,
 0.32093,
 0.40236,
 1.02985,
 0.58917,
 0.29799,
 0.32109,
 0.12474,
 0.24717,
 0.4851,
 0.17017]

In [34]:
len(wbc_model)

25

In [35]:
n_clusters = len(cluster_list)
logsumexp_points = np.log(wbc_model)
model = MultiClusterLinearRegression(n_clusters, X, y)
model.fit(logsumexp_points)

In [36]:
# Generate Plotly plot
subclone_plot_new_model_html = plot_subclones_new_model(cluster_list, times_sample, wbc_model, log_subclone_sample, extrapolate_start_idx, times_aft_tx, times_sliced_aft, treatment_df,treatment_end, model, fi_modeling=True )


DEBUG: plot_subclones_new_model called with clusters=[1, 2, 3], times_sample[1]=59, treatment_end=1636


In [37]:
plot_mcmc_new_model_html = plot_mcmc_model(cluster_list, index_samples_model, times_aft_tx, times_sample, times_sliced_aft, sample_list, wbc_model, log_subclone_sample_mcmc_with_uniform_noise, treatment_df, treatment_end, fi_modeling=True)


In [38]:
create_html_file([wbc_table_html, plot_ccf_html, ccf_tree_html, CLL_plot_html, subclone_plot_html,linear_model_mcmc_html,subclone_plot_new_model_html, plot_mcmc_new_model_html], output_file=outputfile_name)

HTML file saved as FI_subplot_combined_07_wbc_updated.html
