In [4]:
# Import necessary libraries
import pandas as pd
import plotly.graph_objects as go
import dalmatian
from google.cloud import storage
import matplotlib.pyplot as plt
import networkx as nx
from networkx.drawing.nx_pydot import graphviz_layout

import numpy as np

from plotly.subplots import make_subplots
# import model_helper 
# from helper import *
# from plotly_helper import *

In [5]:
# Get input files from Terra through dalmatian
workspace = 'broad-getzlab-pcyc-terra/Getz_Wu_CLL_Pharmacyclics_Exomes_Cleaned_FINALFINAL_Analysis'
wm = dalmatian.WorkspaceManager(workspace)
participants = wm.get_participants()

In [19]:
import subprocess
for patient_id in participants.index:
    source_file = participants.loc[patient_id]['cluster_ccfs']
    # Define a destination path on your local machine, e.g., a 'data' folder
    
    if pd.isna(source_file):
        print(f"Skipping patient {patient_id}: 'cluster_ccfs' path is missing.")
        continue  # Skip to the next iteration of the loop
    
    output_filepath = f"../Outputs/{patient_id}_cluster_ccfs_trimmed.txt"
    trim_file_by_column(source_file, output_filepath, trim_column='postDP_ccf_mean')
    
#     # Construct the full gsutil command
#     gsutil_command = f"gsutil cp {source_file} ."
    
#     # Execute the command in the shell
#     subprocess.run(gsutil_command, shell=True, check=True)

File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH1_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH10_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH14_cluster_ccfs_trimmed.txt'
Skipping patient RP-2080_PCYC_CH15: 'cluster_ccfs' path is missing.
Skipping patient RP-2080_PCYC_CH16: 'cluster_ccfs' path is missing.
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH18_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH19_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH2_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH23_cluster_ccfs_trimmed.txt'
Skipping patient RP-2080_PCYC_CH24: 'cluster_ccfs' path is missing.
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_CH26_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to

File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB34_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB35_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB37_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB38_cluster_ccfs_trimmed.txt'
Skipping patient RP-2080_PCYC_IB39: 'cluster_ccfs' path is missing.
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB4_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB40_cluster_ccfs_trimmed.txt'
Skipping patient RP-2080_PCYC_IB41: 'cluster_ccfs' path is missing.
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB42_cluster_ccfs_trimmed.txt'
Skipping patient RP-2080_PCYC_IB43: 'cluster_ccfs' path is missing.
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_IB44_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved t

File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW35_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW36_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW37_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW38_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW39_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW4_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW40_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW41_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW42_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/RP-2080_PCYC_WW43_cluster_ccfs_trimmed.txt'
File successfully trimmed and saved to '../Outputs/

In [17]:
def trim_file_by_column(input_filepath, output_filepath, trim_column='postDP_ccf_mean'):
    """
    Reads a tab-separated file, finds a specified column, and saves
    a new file with all columns up to and including the trim_column.

    Args:
        input_filepath (str): The path to the input file.
        output_filepath (str): The path to save the trimmed output file.
        trim_column (str): The name of the column to trim the file at.
    """
    try:
        # Read the tab-separated file into a pandas DataFrame
        df = pd.read_csv(input_filepath, sep='\t')
        
        # Get all the column names
        columns = df.columns.tolist()
        
        # Find the index of the specified trim_column
        if trim_column not in columns:
            print(f"Error: The column '{trim_column}' was not found in the file.")
            return

        trim_index = columns.index(trim_column)
        
        # Select all columns from the beginning up to and including the trim_column
        trimmed_df = df.iloc[:, :trim_index + 1]
        
        # Save the new, trimmed DataFrame to a new file, using tabs as separators
        trimmed_df.to_csv(output_filepath, sep='\t', index=False)
        
        print(f"File successfully trimmed and saved to '{output_filepath}'")

    except FileNotFoundError:
        print(f"Error: The file '{input_filepath}' was not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


In [21]:
%pwd

'/Users/lil/PycharmProjects/Fludarabine/GCLL notebooks'

In [22]:
import pandas as pd
import glob
import os

def concatenate_trimmed_files(input_directory, output_filename, file_pattern="*_trimmed.txt"):
    """
    Concatenates multiple trimmed files from a directory into a single file.

    Args:
        input_directory (str): The directory containing the trimmed files.
        output_filename (str): The name for the concatenated output file.
        file_pattern (str): The file pattern to match (e.g., "*.trimmed.txt").
    """
    # Use glob to find all files matching the pattern in the specified directory
    filepaths = glob.glob(os.path.join(input_directory, file_pattern))
    
    if not filepaths:
        print(f"No files found in '{input_directory}' with the pattern '{file_pattern}'.")
        return

    # Create a list to hold the DataFrames
    df_list = []
    
    # Read each file and append its DataFrame to the list
    for file in filepaths:
        try:
            df = pd.read_csv(file, sep='\t')
            df_list.append(df)
            print(f"Successfully read {file}")
        except Exception as e:
            print(f"Error reading {file}: {e}")

    # Concatenate all DataFrames in the list
    if df_list:
        combined_df = pd.concat(df_list, ignore_index=True)
        
        # Save the combined DataFrame to a new file
        combined_df.to_csv(output_filename, sep='\t', index=False)
        print(f"\nAll files successfully concatenated and saved to '{output_filename}'")
    else:
        print("No valid files were read. Concatenation aborted.")

# Example usage
input_folder = "../Outputs"
output_file = "all_trimmed_data.txt"

concatenate_trimmed_files(input_folder, output_file)


Successfully read ../Outputs/RP-2080_PCYC_IB6_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH47_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB97_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH29_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW42_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH43_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB93_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB2_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB79_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB20_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW28_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW46_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB42_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB75_cluster_ccfs_trimme

Successfully read ../Outputs/RP-2080_PCYC_WW41_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW18_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB23_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB14_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH19_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB90_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH40_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_CH9_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB1_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW45_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW15_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_WW22_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB44_cluster_ccfs_trimmed.txt
Successfully read ../Outputs/RP-2080_PCYC_IB8_cluster_ccfs_trimmed

In [7]:
participants

tree_tsv  \
participant_id                                                         
RP-2080_PCYC_CH1   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH10  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH14  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH15                                                NaN   
RP-2080_PCYC_CH16                                                NaN   
...                                                              ...   
RP-2080_PCYC_WW59  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW6   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW7   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW8   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW9   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   

                                                        blacklist_ig  \
participant_id                                                         
RP-2080_PCYC_CH1   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH10  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH14  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH15                                                      
RP-2080_PCYC_CH16                                                      
...                                                              ...   
RP-2080_PCYC_WW59  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW6   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW7   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW8   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW9   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   

                                                    constrained_ccfs  \
participant_id                                                         
RP-2080_PCYC_CH1   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH10  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH14  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH15                                                NaN   
RP-2080_PCYC_CH16                                                NaN   
...                                                              ...   
RP-2080_PCYC_WW59  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW6   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW7   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW8   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW9   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   

                                          cell_population_mcmc_trace  \
participant_id                                                         
RP-2080_PCYC_CH1   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH10  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH14  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_CH15                                                NaN   
RP-2080_PCYC_CH16                                                NaN   
...                                                              ...   
RP-2080_PCYC_WW59  gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW6   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW7   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW8   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   
RP-2080_PCYC_WW9   gs://fc-secure-abe6765b-cffb-4102-a8c0-78b0fa4...   

                                                            samples_  \
participant_id                                                         
RP-2080_PCYC_CH1   [RP-2080_PCYC_CH1_N_01_v2_Exome_OnPrem, RP-208...   
RP-2080_PCYC_CH10  [RP-2080_PCYC_CH10_N_01_v2_Exome_OnPrem, RP-20...   
RP-2080_PCYC_CH14  [RP-2

In [ ]:
cluster_CCF_df = pd.read_csv(participants.loc[patient_id]['cluster_ccfs'], sep='\t')

In [2]:
# Input patient information
patient_id = 'GCLL-0022'
wbc_file = 'CLL8 CLL cell count 05222025 UPDATED.csv'
treatment_file = 'GCLL_treatment.txt'
UMI_start = 1
UMI_end = 5  
# 
treatment_start = 0


In [3]:
# Manually verify the sample list order is correct

In [4]:
sample_list = ['GCLL-0022-T-01','RP-1895_PDO-34670_SM-NPXTD_GCLL-0022-MRD-01_v1_Custom_Selection_OnPrem',
       'RP-1895_PDO-33508_SM-NKK13_GCLL-0022-MRD-02_v1_Custom_Selection_OnPrem',
       'RP-1895_PDO-34670_SM-NPXSH_GCLL-0022-MRD-03_v1_Custom_Selection_OnPrem','RP-1895_PDO-34670_SM-NPXTL_GCLL-0022-MRD-04_v1_Custom_Selection_OnPrem','GCLL-0022-T-02']


In [5]:
len(sample_list)

6

In [6]:
# Output file

In [7]:
outputfile_name = "CLL_subplot_combined_0022_wbc_updated.html"

In [8]:


# Function to load data
def load_data(patient_id, wbc_file, treatment_file):
    # Load WBC and treatment data
    wbc_df = pd.read_csv(wbc_file)
    treatment_df = pd.read_csv(treatment_file, sep='\t')
    
    # Get input files from Terra through dalmatian
    workspace = 'broad-firecloud-ibmwatson/TAG_CLL_Clonal_Kinetic_UMI_PrAN'
    wm = dalmatian.WorkspaceManager(workspace)
    participants = wm.get_participants()
    
    # Load additional data for the patient
    cluster_CCF_df = pd.read_csv(participants.loc[patient_id]['cluster_ccfs'], sep='\t')
    abundance_df = pd.read_csv(participants.loc[patient_id]['abundances_tsv'], sep='\t')
    mcmc_df = pd.read_csv(participants.loc[patient_id]['cell_population_mcmc_trace'], sep='\t')
    tree_df = pd.read_csv(participants.loc[patient_id]['tree_tsv'], sep='\t')
    
    return wbc_df, treatment_df, cluster_CCF_df, abundance_df, mcmc_df, tree_df

# Function to filter data for a specific patient
def filter_patient_data(wbc_df, patient_id):
    wbc_df_patient = wbc_df[wbc_df['Patient'] == patient_id]
    wbc_df_patient.reset_index(drop=True, inplace=True)
    sample_list = wbc_df_patient['Timepoint'].dropna().tolist()
    times_sample = [int(i) for i in wbc_df_patient.loc[wbc_df_patient.Sample.notna(), 'Time_since_start_tx'].tolist()]
    wbc_all = [float(i) for i in wbc_df_patient['WBC'].tolist()]
    
    
    CLL_count = [float(i) for i in wbc_df_patient.loc[wbc_df_patient.Sample.notna(), 'CLL count estm'].tolist()]
    all_times = [int(i) for i in wbc_df_patient['Time_since_start_tx'].to_list()]
    
    return wbc_df_patient, times_sample, CLL_count, wbc_all,all_times





Update patient specific information in the below cell 

In [9]:
end_treatment_df = pd.read_csv("CLL8_end_treatment.csv")

In [10]:
# Get the treatment duration 

treatment_end = end_treatment_df[end_treatment_df.Patient == patient_id].Treatment_duration.iloc[0]

In [11]:
treatment_end

142

In [12]:

wbc_df, treatment_df, cluster_CCF_df, abundance_df, mcmc_df, tree_df = load_data(patient_id, wbc_file, treatment_file)

# Filter data for the specific patient
wbc_df_patient, times_sample, CLL_count_sample,wbc_count, all_times = filter_patient_data(wbc_df, patient_id)

# Plot CLL count over time and save as HTML
CLL_plot_html = plot_CLL_count(patient_id, times_sample, CLL_count_sample, UMI_start, UMI_end, treatment_start, treatment_end, )
    




In [13]:
times_sample

[-19, 1140, 1211, 1302, 1414, 2029]

In [14]:
wbc_count

[51.88, 3.9, 2.5, 2.8, 3.1, 4.3, 4.1, 4.0, 3.4, 4.1, 5.5, 3.5, 3.4, 2.2]

In [15]:
CLL_count_sample

[46.1732, 0.02983445, 0.06655, 0.08465064, 0.24514, 0.88]

In [16]:
wbc_table_html = plot_metadata_table(wbc_df_patient, patient_id )

In [17]:
 plot_tree_html = plot_tree_plotly(tree_df, 0)

In [18]:
 plot_ccf_html = plot_ccf(cluster_CCF_df, times_sample, treatment_df,)

In [45]:
branch_annotations = {
    1: "FAT4_p.R1671C",
    2: "POT1_p.Y242C,CHD8_p.F849L, CTNNA2_p.R136H,chr13_cnLOH, chr18_cnLOH", 
    3: "TP53_p.V157F,del(17p),ABI1_p.P207fs ,NUP210L_p.K1135N",
    4: "POT1_p.Y36C, KRAS_p.A146T,chr18_cnLOH",
    5: "PRPF40B_p.A369V",
    
}

In [47]:
ccf_tree_html = plot_ccf_tree_combined(
    tree_df=tree_df,
    tree_selected=0,
    ccf_df=cluster_CCF_df,
    times_sample=times_sample,
    treatment_df=treatment_df,
    branch_annotations=branch_annotations

)

POT1_p.Y242C<br>CHD8_p.F849L<br>CTNNA2_p.R136H<br>chr13_cnLOH<br>chr18_cnLOH
TP53_p.V157F<br>del(17p)<br>ABI1_p.P207fs<br>NUP210L_p.K1135N
POT1_p.Y36C<br>KRAS_p.A146T<br>chr18_cnLOH


In [20]:
cluster_list, cluster_abundance = model_helper.get_abundance(abundance_df, mcmc_df, sample_list)
subclone_sample, log_subclone_sample = model_helper.calc_subclone(CLL_count_sample, cluster_abundance, cluster_list)
all_abundance = model_helper.get_all_abundance(cluster_list, mcmc_df, sample_list, times_sample, )

In [21]:
#  Add noise to all abundance

import random 
random.seed(42)
def add_uniform_noise_and_normalize(lst, low=0, high=0.01):
    
    # Add uniform noise
    noisy_lst = [x + random.uniform(low, high) for x in lst]

    
    # Normalize the list
    total_sum = sum(noisy_lst)
    
    normalized_lst = [x / total_sum for x in noisy_lst]

    return normalized_lst


subclone_cluster_iter = {}
# Iterate through each cluster
for cluster, iterations in all_abundance.items():
   
    # Iterate through each iteration in the cluster
    for iteration, value in iterations.items():
        # If the iteration is not in the new dict, add it
        if iteration not in subclone_cluster_iter:
            subclone_cluster_iter[iteration] = {}
        # Add the cluster and its value to this iteration
        subclone_cluster_iter[iteration][cluster] = value

        
        
noise_added_iter = {}

for iteration, abundances in subclone_cluster_iter.items():
    
    transposed_data = {i: list(values) for i, values in enumerate(zip(*abundances.values()), start=1)}
    
    noise_added_iter[iteration] = {}
    for time_point, abundance in transposed_data.items():
        
#         print(time_point, abundance)
        noise_abundance = add_uniform_noise_and_normalize(abundance)
    
#         print(noise_abundance)

        noise_added_iter[iteration][time_point] = add_uniform_noise_and_normalize(abundance)

    
noise_added_all_abundance = {}
for iteration, abundances in noise_added_iter.items():
    original_format = {i + 1: list(values) for i, values in enumerate(zip(*abundances.values()))}
    noise_added_all_abundance[iteration] = original_format
    
    
noise_added_original_all_abundances = {}

for iteration, abundances in noise_added_all_abundance.items():
    
    for cluster, abundance_value in abundances.items():
        if cluster not in noise_added_original_all_abundances:
            noise_added_original_all_abundances[cluster] = {}
        noise_added_original_all_abundances[cluster][iteration] = abundance_value
            

In [22]:
subclone_sample_mcmc_with_uniform_noise, log_subclone_sample_mcmc_with_uniform_noise = model_helper.calc_subclone(CLL_count_sample, noise_added_original_all_abundances, cluster_list, input_type = "mcmc")

In [23]:
times_aft_tx = [x for x in all_times if x > treatment_end]
times_aft_tx.insert(0, treatment_end)

# Set the extrapolate time after treatment
extrapolate_start_idx = 1

In [24]:
times_sample

[-19, 1140, 1211, 1302, 1414, 2029]

In [25]:
times_aft_tx

[142, 383, 467, 544, 691, 782, 908, 999, 1140, 1211, 1302, 1414, 2029]

In [26]:
# Generate Plotly plot
subclone_plot_html = plot_subclones(cluster_list, times_sample, CLL_count_sample, log_subclone_sample, extrapolate_start_idx, times_aft_tx, treatment_df, treatment_end)


In [27]:
linear_model_mcmc_html = plot_linear_model_mcmc(cluster_list,times_sample,  CLL_count_sample, log_subclone_sample_mcmc_with_uniform_noise,extrapolate_start_idx,times_aft_tx,treatment_df, treatment_end)  

In [28]:
# Convert the column "CLL count estm" to float 
wbc_df_patient['CLL count estm'] = wbc_df_patient['CLL count estm'].astype(float) 
times_sliced_aft = [int(i) for i in wbc_df_patient[wbc_df_patient['CLL count estm'] > 0]['Time_since_start_tx'].values  if int(i) > 0]

/var/folders/x6/7zg8fddx4dlgx2lv4sv34_g40000gp/T/ipykernel_96046/981427378.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [29]:
times_aft_tx

[142, 383, 467, 544, 691, 782, 908, 999, 1140, 1211, 1302, 1414, 2029]

In [30]:
# Needs to manually check times_sliced_aft

In [31]:
times_sliced_aft

[467, 691, 782, 908, 999, 1140, 1211, 1302, 1414, 2029]

In [32]:
len(times_sliced_aft)

10

In [33]:
index_samples_model = slice(1,6)

# index_samples_model is the index of the samples after treatment. For instance, slice(1,7) means sample 2, 3, 4, 5,6, 7

X, y = create_inputs(times_sliced_aft, log_subclone_sample_mcmc_with_uniform_noise,2, index_samples_model, times_sample)



In [34]:
log_subclone_sample_mcmc_with_uniform_noise[1][2]

[2.6923066499585473,
 -4.848465127476099,
 -4.159772809897362,
 -8.328398008375016,
 -8.502358740821702,
 -6.3366714049848945]

In [35]:
y

[None,
 None,
 None,
 None,
 None,
 array([-4.84846513, -5.0472956 , -4.75966787, -5.06252048, -7.28721054]),
 array([-4.15977281, -3.36232329, -4.42904747, -5.65407843, -7.0260049 ]),
 array([-8.32839801, -2.77097058, -5.14893348, -4.21513557, -6.6653751 ]),
 array([-8.50235874, -1.64998768, -3.82310249, -4.54320015, -3.88693412]),
 array([-6.3366714 , -0.9424698 , -0.8909029 , -4.36893927, -2.71725613])]

In [36]:
wbc_aft_tx = wbc_df_patient[wbc_df_patient.Time_since_start_tx > treatment_end]['CLL count estm'].to_list()
wbc_model = [i for i in wbc_aft_tx if i > 0]

In [37]:
wbc_model

[0.00029033,
 0.00257116,
 0.00374381,
 0.00645212,
 0.0114789,
 0.02983445,
 0.06655,
 0.08465064,
 0.24514,
 0.88]

In [38]:
len(wbc_model)

10

In [39]:
n_clusters = len(cluster_list)
logsumexp_points = np.log(wbc_model)
model = MultiClusterLinearRegression(n_clusters, X, y)
model.fit(logsumexp_points)

In [40]:
# Generate Plotly plot
subclone_plot_new_model_html = plot_subclones_new_model(cluster_list, times_sample, wbc_model, log_subclone_sample, extrapolate_start_idx, times_aft_tx, times_sliced_aft, treatment_df,treatment_end, model )


In [41]:
plot_mcmc_new_model_html = plot_mcmc_model(cluster_list, index_samples_model, times_aft_tx, times_sample, times_sliced_aft, sample_list, wbc_model, log_subclone_sample_mcmc_with_uniform_noise, treatment_df, treatment_end)

In [48]:
create_html_file([wbc_table_html, plot_ccf_html, ccf_tree_html, CLL_plot_html, subclone_plot_html,linear_model_mcmc_html,subclone_plot_new_model_html, plot_mcmc_new_model_html], output_file=outputfile_name)

HTML file saved as CLL_subplot_combined_0022_wbc_updated.html
